### PR TITLE
Update intro chapter

### PR DESCRIPTION
**Pull request by jimhshen**
Can you check the Grigsby citation? Its citekey is just "grigsby" in Zotero, and currently outputs the following:

Grigsby, John, Erik Hurst, and Ahu Yildirmaz. n.d. “Aggregate Nominal Wage Adjustments: New Evidence from Administrative Payroll Data.” American Economic Review. Accessed November 10, 2020. https://www.aeaweb.org/articles?id=10.1257/aer.20190318&&from=f.

The DOI for AEA doesn't work yet, and there's no way to do "forthcoming" as the date. We could cite the [NBER working paper ](https://www.nber.org/papers/w25628) instead, not sure which one is the correct solution

### CODE REVIEW

**Comment by larsvilhuber** [comment]
DOI is assigned when it is no longer forthcoming. 

Try https://forums.zotero.org/discussion/68198/apa-style-in-press-articles, or use date = 2020 and volume = forthcoming

**Review by larsvilhuber — CHANGES_REQUESTED** [review]
@jimhshen Just a note: NOT approved, fix the citation thing first.

Note one alternative: add a second (3rd?) bib file, manually maintained. The problem with "forthcoming" is in Zotero, not bibtex.

**Comment by jimhshen** [comment]
This look better? 

Grigsby, John, Erik Hurst, and Ahu Yildirmaz. 2020. “Aggregate Nominal Wage Adjustments: New Evidence from Administrative Payroll Data.” American Economic Review Forthcoming. https://www.aeaweb.org/articles?id=10.1257/aer.20190318&&from=f.

**Comment by jimhshen** [comment]
Also updated the table with the new variant that Anja wanted.

**Review by larsvilhuber — APPROVED** [review]
Looks fine.

**Pull request merged**
